# @package _global_
pickle_normal: /neurospin/dico/data/deep_folding/papers/midl2022/crops/CINGULATE/mask/sulcus_based/2mm/centered_combined/hcp/Rskeleton.pkl
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/papers/midl2022/HCP_half_1bis.csv
nb_subjects: -1
