# @package _group_
defaults:
  - hydra: local
  - hydra/job_logging: custom
  - dataset: cingulate
  - model: SimCLR
  - backbone: DenseNet
  - preprocessing: default
  - platform: cuda_not_brainvisa

